filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
    - versionStream/src/fake-secrets.yaml.gotmpl
repositories:
- name: jenkins-x
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: external-secrets
  url: https://godaddy.github.io/kubernetes-external-secrets
- name: jx-labs
  url: https://storage.googleapis.com/jenkinsxio-labs-private/charts
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: banzaicloud-stable
  url: https://kubernetes-charts.banzaicloud.com
releases:
- chart: jenkins-x/jxboot-helmfile-resources
  version: 0.0.283
  name: jxboot-helmfile-resources
  namespace: jx
  values:
  - charts/jenkins-x/jxboot-helmfile-resources/values.yaml
  - versionStream/charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
- chart: external-secrets/kubernetes-external-secrets
  version: 4.0.0
  name: kubernetes-external-secrets
  namespace: secret-infra
  values:
  - versionStream/charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
- chart: jx-labs/jenkins-x-crds
  version: 0.0.7
  name: jenkins-x-crds
  namespace: jx
  values:
  - versionStream/charts/jx-labs/jenkins-x-crds/values.yaml
- chart: jenkins-x/tekton
  version: 0.0.56
  name: tekton
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/tekton/values.yaml.gotmpl
- chart: jenkins-x/lighthouse
  version: 0.0.683
  name: lighthouse
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/lighthouse/values.yaml.gotmpl
- chart: jenkins-x/bucketrepo
  version: 0.1.39
  name: bucketrepo
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/bucketrepo/values.yaml.gotmpl
- chart: stable/docker-registry
  name: docker-registry
  namespace: jx
  values:
  - versionStream/charts/stable/docker-registry/values.yaml.gotmpl
- chart: banzaicloud-stable/vault-operator
  version: 1.3.0
  name: vault-operator
  namespace: secret-infra
- chart: jx-labs/vault-instance
  version: 0.0.1
  name: vault-instance
  namespace: secret-infra
- chart: jx-labs/pusher-wave
  version: 1.0.0
  name: pusher-wave
  namespace: secret-infra
templates: {}
missingFileHandler: ""
