# Source: docker-registry/templates/secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: docker-registry-secret
  namespace: jx
  annotations:
    secret.jenkins-x.io/schema-object: '{"name":"docker-registry-secret","properties":[{"name":"haSharedSecret","question":"The
      ha secret","help":"Shared secret for Registry","generator":"password","minLength":16,"maxLength":16}],"mandatory":true}'
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: secret-infra
  data:
  - name: haSharedSecret
    key: secret/data/docker/registry/secret
    property: haSharedSecret
  template:
    metadata:
      labels:
        app: docker-registry
        chart: docker-registry-1.9.4
        heritage: Helm
        release: docker-registry
      annotations:
        secret.jenkins-x.io/schema-object: '{"name":"docker-registry-secret","properties":[{"name":"haSharedSecret","question":"The
          ha secret","help":"Shared secret for Registry","generator":"password","minLength":16,"maxLength":16}],"mandatory":true}'
    type: Opaque
