# Source: jxboot-helmfile-resources/charts/controllerbuild/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jxboot-helmfile-resources-controllerbuild
  labels:
    app: controllerbuild
    chart: controllerbuild-2.0.1143
    release: jxboot-helmfile-resources
    heritage: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
  namespace: jx
